Adding draw arrow feature for glassbrain
Eelbrain/Eelbrain pull request #30
Opened 2018-12-09 23:57 UTC by proloyd

Now glassbrain accepts ``draw_arrows`` argument, which if set to ``True`` arrows pointing the direction of activation is drawn over the glassbrain plots. Naturally, for this to work ``NDVar`` needs to contain space dimension (i.e 3D vector data). By default it is set to ``False``.

2018-12-10 02:35 UTC, christianbrodbeck requested changes
Look good already! Some potential changes to consider, let me know if something is not clear. Thanks!

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/_stats/testnd.py
> +        return self.difference.norm('space').mask(mask), self.difference * (self.p <= p)
This function should not be changed to maintain consistency with other NDTests. If it just returns the vector difference (as the superclass method should do) you should just be able to take the norm afterwards, no?

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> +        bfly_data = [z.sub(source=hemi, name=hemi.capitalize()) for hemi in hemis]
I think this `butterfly_data()` is also used for surface source spaces, and there we would need norm data – you'll probably need a parameter that says whether `butterfly_data()` should return vector data if available.

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +                 interpolation='nearest', **kwargs):
I would say `draw_arrows` should be true by default, and it should be disabled when `ndvar` is scalar. Or do you think there will be more cases where we want to plot vector data without arrows?

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +            q.remove()
Duplicate method?

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +    def butterfly(cls, y, cmap=None, vmin=None, vmax=None, draw_arrows=False,
The order of arguments should be consistent with `__init__`

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +        draw_arrows: boolean
The order in the documentation should be same as in the function signature

2018-12-10 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +    non_finite_mask = np.logical_not(np.isfinite(data))
Do you really need this check? Since this happens in the animation, it might be more efficient to guarantee that the data is ok when generating it?

2018-12-10 06:04 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +    def butterfly(cls, y, cmap=None, vmin=None, vmax=None, draw_arrows=False,
Done!

2018-12-10 06:04 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +        draw_arrows: boolean
Thanks for pointing this out!

2018-12-10 06:06 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +    non_finite_mask = np.logical_not(np.isfinite(data))
Good point, I bypassed this check by setting a global check while converting ndvar to nifti/ volume format.

2018-12-10 06:09 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +            q.remove()
I did not get this comment. I just made a separate function so that readability improves. 
Also, if we decide to add this feature on GUI in future, then it will be helpful in key-binding.

2018-12-10 06:10 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +                 interpolation='nearest', **kwargs):
I made the changes.

2018-12-10 06:48 UTC, proloyd commented on eelbrain/plot/_base.py
> +        bfly_data = [z.sub(source=hemi, name=hemi.capitalize()) for hemi in hemis]
Okay! Made the changes. https://github.com/proloyd/Eelbrain/blob/3d538b0c29bbac23f71749a99b23e076cc60184f/eelbrain/plot/_base.py#L667

2018-12-10 06:55 UTC, proloyd commented on eelbrain/_stats/testnd.py
> +        return self.difference.norm('space').mask(mask), self.difference * (self.p <= p)
Now rolled back to previous version of the function. Actually the np.ma.masked_array function does not do broadcasting, so did that. https://github.com/proloyd/Eelbrain/blob/e08725268dc4327454f5e0994d175c98a4da90f5/eelbrain/_data_obj.py#L3993

2018-12-10 07:06 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +            q.remove()
Oh..I see now. Cool. I dont know how this got duplicated.

2018-12-10 07:19 UTC, proloyd reviewed
np.ma.maskedarray does not support broadcasting, so had to manually do it.

2018-12-10 07:23 UTC, proloyd commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
taking norm does not preserve the mask, so added this few lines to take care of that.

2018-12-10 07:25 UTC, proloyd commented on eelbrain/_data_obj.py
> +        # Masked array creation does not support broadcasting
Apparently , masked array creation does not support broadcasting, so needed to mask three directions separately.

2018-12-10 12:14 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +                                  'Continuing without arrows...')
I would skip the warning (especially now that `draw_arrows` is on by default)

2018-12-10 12:14 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> +        return_vector_data = False,
To be consistent with the rest of the function signature you could add the type specification (`: bool`)

2018-12-10 12:14 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
Oh but it should :) do you want to look into fixing it? I can also look into it if it looks to complex.

2018-12-10 12:45 UTC, christianbrodbeck commented on eelbrain/_data_obj.py
> +        # Masked array creation does not support broadcasting
Hmm, according to the documentation it does not handle broadcasting. If it were to it should handle it in a general way, but that might be tricky. Say, the NDVar has shape `(3, 3)`, and `.mask()` is called with a shape `(3,)` array, which dimension do you broadcast? It could assume always the first dimension? But probably easier would be to broadcast the mask in `NDDifferenceTest.masked_difference` with a check like `if isinstance(self, Vector)` (that will also be True for subclasses of `Vector`)

2018-12-10 12:47 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +        p_glassbrain = GlassBrain(brain_data, cmap, vmin, vmax, dest, draw_arrows, mri_resolution, mni305,
Looks like `draw_arrows` is now in the wrong place here

2018-12-10 12:49 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +    def butterfly(cls, y, cmap=None, vmin=None, vmax=None, draw_arrows=False,
But looks like it changed for `__init__` since then :)

2018-12-10 16:18 UTC, proloyd commented on eelbrain/plot/_base.py
> +        return_vector_data = False,
Cool, Doing that. By the way, I was not familiar with this type of function signature. Is it some special function signature type?

2018-12-10 16:24 UTC, proloyd commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
No, it should not. Like you said previously, suppose your original array a was (3, 3), and you took norm(a), then how will it decide the mask for that scalar? Same applies when it's a 1D (3, ) array. Right? I though of adding this `mask`ed `norm` in the data_obj, but it does not make any sense.

2018-12-10 16:26 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> +        return_vector_data = False,
https://docs.python.org/3.6/library/typing.html

2018-12-10 16:30 UTC, proloyd commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
I guess this only the place, where we will use masking the norm from the vectors, so it makes sense to put it over here.

2018-12-10 16:34 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
It should behave like `numpy` does. If you're worried about the norm of a vector for which only some elements are masked, we could raise an error for that for now. For the significance case, it should always be either all or none of the elements.

2018-12-10 16:38 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +                                  'Continuing without arrows...')
Okay. Doing that.

2018-12-10 17:01 UTC, proloyd commented on eelbrain/_data_obj.py
> +        # Masked array creation does not support broadcasting
Implemented that.

2018-12-10 17:12 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +                        warnings.warn('Cannot use maximum intensity projection'
I would just raise a `ValueError` if parameters are inconsistent/impossible.

2018-12-10 17:13 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +                        warnings.warn('Cannot use maximum intensity projection'
```suggestion
                        raise ValueError(f"Cannot use plot_abs={plot_abs} with draw_arrows={draw_arrows}")
```

2018-12-10 17:20 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +
No need for this, it's handled in get_data (https://eelbrain.readthedocs.io/en/latest/generated/eelbrain.NDVar.get_data.html#eelbrain.NDVar.get_data)

2018-12-10 18:51 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +
Which one did you pointed here? The ndvar.copy('copy') or the Note? 
ndvar.copy('copy') was needed here, otherwise `ndvar.x[ndvar.x.mask] = 0` was changing the original array.
I should have removed the Note, btw.

2018-12-10 18:58 UTC, proloyd commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
Actually, numpy norm does not acre about the mask. It just returns a vanilla ndarray, removing all masking info. So, I tried to add this masking thing in  ndvar.norm but it does not make sense in the case  when some elements along the axis over which norm is taken are masked, not all. So, I just moved this code in this position.

2018-12-10 19:14 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +                        warnings.warn('Cannot use maximum intensity projection'
Done.

2018-12-10 19:25 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +
Oh, I now got it. You meant the masking. Taking care of it.

2018-12-10 20:50 UTC, proloyd commented on eelbrain/_data_obj.py
> +                raise NotImplementedError(f"masked data norm along dim={dim}")
Until we figure out a sensible way of returning norm of masked data, attempting 'norm' for masked data along any dim except space will raise error.

2018-12-10 20:51 UTC, proloyd commented on eelbrain/plot/_base.py
> +        if y.has_dim('space'):
I moved this to ndvar.norm. Let me know if that makes sense.

2018-12-10 21:08 UTC, christianbrodbeck commented on eelbrain/_data_obj.py
> +                raise NotImplementedError(f"masked data norm along dim={dim}")
What about 

```
all_masked = np.all(self.x.mask, axis)
any_masked = np.any(self.x.mask, axis)
if np.any(all_masked != any_masked):
    raise ValueError(f"Norm along {dim!r} with inconsistent mask")
mask = all_masked
```

2018-12-10 21:08 UTC, christianbrodbeck commented on eelbrain/_data_obj.py
> +                raise NotImplementedError(f"masked data norm along dim={dim}")
What about 
```
all_masked = np.all(self.x.mask, axis)
any_masked = np.any(self.x.mask, axis)
if np.any(all_masked != any_masked):
    raise ValueError(f"Norm along {dim!r} with inconsistent mask")
mask = all_masked
```

2018-12-10 22:23 UTC, proloyd commented on eelbrain/_data_obj.py
> +        if isinstance(self.x, np.ma.masked_array):
great idea! But I guess this will almost always raise error if the dim is not `space`.

2018-12-10 23:10 UTC, christianbrodbeck commented on eelbrain/_data_obj.py
> +        if isinstance(self.x, np.ma.masked_array):
That's fine, if someone has a use case that makes sense it can be modified. There might also be other cases where this would work, for example, in sensor space data you could mask a specific sensor.

2018-12-10 23:27 UTC, proloyd commented on eelbrain/_data_obj.py
> +        if isinstance(self.x, np.ma.masked_array):
Yeah! Sure. Haven't thought of that.

2018-12-12 02:33 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> -        if y.has_dim('space'):
So currently I think this function won't work as expected for `Vector` tests, right? There, `y = data.masked_difference()` will be vector data, whereas significance will not. But I can look into that if you'd rather not :) If you do, you could also add some tests to test the new features in `test_glassbrain.py`.

2018-12-12 02:35 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +from nilearn.image.resampling import get_bounds
I think there was a problem with `nilearn` imports at module level because it imports `pyplot` immediately, messing up the matplotlib backend situation

2018-12-12 02:41 UTC, christianbrodbeck commented on eelbrain/plot/_base.py
> -        if y.has_dim('space'):
Ah I realize it's tested already because `draw_arrows` is on by default:)

2018-12-12 02:44 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +    def __init__(self, ndvar, cmap=None, vmin=None, vmax=None, dest='mri',
Can you keep the previous default arguments?

2018-12-12 03:29 UTC, proloyd commented on eelbrain/plot/_base.py
> -        if y.has_dim('space'):
Yeah, I took care of that already in vector test. :)

2018-12-12 03:32 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +from nilearn.image.resampling import get_bounds
yeah I remeber, but this time nothing happened, it passed the tests without any hiccups. If you want I can move it inside glassbrain.

2018-12-12 06:44 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +from nilearn.image.resampling import get_bounds
Actually, nilearn.image does not import pyplot, so there is no chance of messing up backend. :)

2018-12-12 15:10 UTC, proloyd commented on eelbrain/plot/_base.py
> -        if y.has_dim('space'):
By the way, I am not sure how to add tests for the new features. Any hint on that?

2018-12-12 17:03 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +    def __init__(self, ndvar, cmap=None, vmin=None, vmax=None, dest='mri',
Sure, I changed it here, and also for the `butterfly` method.

2018-12-13 01:56 UTC, christianbrodbeck reviewed
Ok, just some stylistic nitpicking, I'll make a PR to show you how to go about testing

2018-12-13 01:56 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +        if self._arrows: self._add_arrows(index)
This style is discouraged, it's clearer to just write 

```
if x:
    do_a()
    do_b()
```

2018-12-13 01:56 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +            (``True``).
The parentheses around True seem off.

2018-12-13 01:57 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +from nilearn.image.resampling import get_bounds
Yeah I think you're right, fine to leave it then

2018-12-13 04:04 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +        if self._arrows: self._add_arrows(index)
I see. Will take a note of that.

2018-12-13 04:04 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +            (``True``).
Okay. I guess I fixed it

2018-12-13 04:10 UTC, christianbrodbeck commented on eelbrain/plot/_glassbrain.py
> +            (i.e 3D vectors). By default it is set to (``True``).
Shouldn't it be this?
```suggestion
            (i.e 3D vectors). By default it is set to ``True``.
```

2018-12-13 04:33 UTC, proloyd commented on eelbrain/plot/_glassbrain.py
> +            (i.e 3D vectors). By default it is set to (``True``).
Actually in plot_abs it was like (``False``), so I used the same. Changing it then. :)

2018-12-13 05:14 UTC, proloyd commented on eelbrain/plot/tests/test_glassbrain.py
> +    # masked data
I added this test for masked data. Is it cumbersome to create the masked array like this? In case you find this unfit we can remove this part.  

Btw thanks for letting me know how to implement this tests. So far I was testing this manually and that was a pain. :( Thank you very much for the guide. :)

2018-12-13 12:27 UTC, christianbrodbeck commented on eelbrain/plot/tests/test_glassbrain.py
> +    p = plot.GlassBrain(y, show=False)
You should not need `show=False`, that should be implied by the `@hide_plots` decorator
```suggestion
    p = plot.GlassBrain(y)
```

2018-12-13 12:30 UTC, christianbrodbeck approved these changes
Let me know when it's ready to be merged from your end!

2018-12-13 12:30 UTC, christianbrodbeck commented on eelbrain/plot/tests/test_glassbrain.py
> +    # masked data
Yes great. You could in principle hard code parameters like `c` because the data will always be the same for the test, but it's a good test to add.

2018-12-13 15:14 UTC, proloyd commented on eelbrain/plot/tests/test_glassbrain.py
> +    p = plot.GlassBrain(y, show=False)
Cool!

2018-12-13 15:51 UTC, proloyd commented on eelbrain/plot/tests/test_glassbrain.py
> +    # masked data
Cool. Now incorporated that. :)

2018-12-13 15:56 UTC, proloyd commented
Once the appveyor build is passed, the branch will be ready to be merged. It is taking so long. I dunno why?

2018-12-13 16:03 UTC, merged

2018-12-13 16:03 UTC, christianbrodbeck commented
Great, Thanks!

2018-12-13 16:21 UTC, proloyd commented
My pleasure!