Trf len
Eelbrain/Eelbrain pull request #39
Opened 2020-02-27 17:07 UTC by jpkulasingham

2020-02-28 01:29 UTC, christianbrodbeck requested changes
Thanks! I've added some initial comments and questions, let me know if any of them are not clear.

2020-02-28 01:29 UTC, christianbrodbeck commented on eelbrain/_experiment/mne_experiment.py
> +            items.append(_time_window_str((tstart1, tstop1)))
Can you drop this for now (for this PR)? I think we'll have to handle this primarily through the `TRFExperiment` class.

2020-02-28 01:29 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +                print(f'Warning: len(tstart) matches len(x) = {len(x)} but not # of predictor dimensions = {n_x}. Infering from data._x_meta')
I would not warn every time, this is a valid way of specifying `tstart`

2020-02-28 01:29 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +    if isinstance(i_start, (tuple, list, np.ndarray)):
Doesn't the outer function make sure that `i_start` is always an integer array? Generally, it's a good idea to make sure the data conform to a specific type in the outermost function, then you can avoid making multiple redundant checks inside of loops.

2020-02-28 01:29 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +        data.y_name, data.x_name, min(tstart), max(tstop), scale_data, delta, mindelta, error,
It would probably be useful for the result to preserve the input argument (whether a scalar or a sequence) so you can later double check what you used for fitting the model – the min/max could be taken internally in the result object where necessary.

2020-02-28 01:29 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +        for i_st in range(n_stims):
`for` loops are slow – could we instead just set `new_error` to a large number on unused indices? `np.inf`?

2020-02-28 01:29 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +        h = h_new
Woulnd't it be more efficient to represent `h` like this from the beginning – with time aligned between predictors and zeros at disabled elements – then a lot of other functions, like `convolve`, would not have to be modified at all?

2020-02-28 01:29 UTC, christianbrodbeck commented on env-dev.yml
> +name: eelfork
This should not be in the PR :) you can also specify the name when creating the environment list

`$ conda env create --file env.yml -n eelfork`

2020-02-28 21:14 UTC, jpkulasingham commented on eelbrain/_experiment/mne_experiment.py
> +            items.append(_time_window_str((tstart1, tstop1)))
Ok. Will remove

2020-02-28 21:14 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +                print(f'Warning: len(tstart) matches len(x) = {len(x)} but not # of predictor dimensions = {n_x}. Infering from data._x_meta')
Removed

2020-02-28 21:15 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +    if isinstance(i_start, (tuple, list, np.ndarray)):
I can remove this check, but `test_boosting_func()` calls `boost()` directly, so the test doesn't pass. Should I modify `test_boosting_func()` to give in a nparray tstart tstop?

2020-02-28 21:16 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +        data.y_name, data.x_name, min(tstart), max(tstop), scale_data, delta, mindelta, error,
Ok will add

2020-02-28 21:16 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +        for i_st in range(n_stims):
Will change

2020-02-28 21:17 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +        h = h_new
Yes, but then several other parts of the function have to be changed in order to align for updating the error. And `convolve` may have to be modified anyway since the padding will differ based on where the convolution should start and stop. Is this essential?

2020-02-28 21:17 UTC, jpkulasingham commented on env-dev.yml
> +name: eelfork
Removed

2020-02-29 12:39 UTC, christianbrodbeck commented on env-dev.yml
> +name: eelfork
Did you forget to push the modification?

2020-03-03 01:40 UTC, christianbrodbeck requested changes
Could you change the way the result is initialized such that `result.tstart` and `.tstop` are scalars if the user-provided argument is scalar? Turning them into arrays breaks a couple of things that currently work, like comparison `result.tstart == 0`.

Let me know when that API issue is done, then I'll have a closer look at the implementation issue.

2020-03-03 01:40 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +    if isinstance(i_start, (tuple, list, np.ndarray)):
Yes that's okay, since `boost` is not a public function it's okay to change its API (and corresponding tests)

2020-03-03 01:40 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +            items.append('%g - %g' % (t1, t2))
The boosting result has to be able to handle `tstart` and `tstop` as scalars, since they will be scalars in older, pickled results. I also think that it would be much more readable to only display one range if a single range was used. If multiple ranges were used, might it be more readable to interleave them with the predictors? i.e., 

`<boosting y ~ word (0 - 0.400) + sentence (0 - 1.300)>`
vs
`<boosting y ~ word + sentence, 0 - 0.400, 0 - 1.300>`

2020-03-03 01:40 UTC, christianbrodbeck commented on eelbrain/_trf/tests/test_boosting.py
> +    x = NDVar(np.random.normal(0, 1, 1000), UTS(0, 0.1, 1000),name='x')
I would use a seeded random state to avoid random surprises in test runs
```suggestion
    rng = np.random.RandomState(0)
    x = NDVar(rng.normal(0, 1, 1000), UTS(0, 0.1, 1000), name='x')
```
...

2020-03-03 01:40 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +        h = h_new
I'll have to think about it when I look into the code in details, leave that for now

2020-03-03 16:51 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +    if isinstance(i_start, (tuple, list, np.ndarray)):
Ok changed `test_boosting_func()`

2020-03-03 16:52 UTC, jpkulasingham commented on eelbrain/_trf/_boosting.py
> +            items.append('%g - %g' % (t1, t2))
changed accordingly

2020-03-03 16:52 UTC, jpkulasingham commented on eelbrain/_trf/tests/test_boosting.py
> +    x = NDVar(np.random.normal(0, 1, 1000), UTS(0, 0.1, 1000),name='x')
added seed

2020-03-14 02:41 UTC, christianbrodbeck commented on eelbrain/_trf/_boosting.py
> +        data.y_name, data.x_name, min(tstart), max(tstop), scale_data, delta, mindelta, error,
I would keep the user input and variable you use internally separate. For example, the current 
```
    if len(tstart) == 1:
        tstart = tstart[0]
```
would get it wrong if the user used `tstart=[0]`, or if the user used `tstart=0` and there are more than one `x`.

2020-04-11 12:33 UTC, christianbrodbeck commented on eelbrain/_trf/tests/test_boosting.py
> +    tstop = np.asarray([10, 10, 10])
```suggestion
    tstart = np.array([0, 0, 0], np.int64)
    tstop = np.array([10, 10, 10], np.int64)
```

2020-04-11 12:33 UTC, christianbrodbeck commented on eelbrain/_trf/tests/test_boosting.py
> +    tstop = np.asarray([10])
```suggestion
    tstart = np.array([0], np.int64)
    tstop = np.array([10], np.int64)
```

2020-04-11 12:53 UTC, christianbrodbeck commented on eelbrain/_trf/tests/test_boosting.py
> +    tstop = np.asarray([10])
(On a 32 bit OS, using integers defaults to 32 bit integers (long)...)

2020-04-11 13:37 UTC, christianbrodbeck commented on eelbrain/_trf/tests/test_boosting.py
> +    tstop = np.asarray([10, 10, 10])
I think you'll need to commit this one too, no?

2020-04-11 15:00 UTC, christianbrodbeck approved these changes

2020-04-11 15:00 UTC, christianbrodbeck commented
Great, ready to merge from your end?

2020-04-11 15:14 UTC, jpkulasingham commented
> Great, ready to merge from your end?

Yup. Fine with me :)

2020-04-11 15:20 UTC, merged

2020-04-11 15:20 UTC, christianbrodbeck commented
Thanks @jpkulasingham !